### ISSUE TITLE
good 

### ISSUE THREAD

**Issue by colinqin7686** [xueyaqing/MOT_results_visualize#1]

**Comment by xueyaqing** [comment]
发东西还需要你同意吗？好好读读代码吧




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "xueyaqing/MOT_results_visualize"                                                                                    <notifications@github.com&gt;;
发送时间:&nbsp;2021年3月5日(星期五) 上午10:32
收件人:&nbsp;"xueyaqing/MOT_results_visualize"<MOT_results_visualize@noreply.github.com&gt;;
抄送:&nbsp;"Subscribed"<subscribed@noreply.github.com&gt;;
主题:&nbsp;[xueyaqing/MOT_results_visualize] 少了一堆文件还好意思发？？？ (#1)
